services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: deployx
      POSTGRES_USER: deployx
      POSTGRES_PASSWORD: deployx
    ports:
      - "5432:5432"
    volumes:
      - deployx-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deployx -d deployx"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  deployx-postgres:
