events {}

http {
    upstream deployx_api { server api:8080; }
    upstream deployx_dashboard { server frontend:80; }

    server {
        listen 80;
        server_name _;

        location /api/ {
            proxy_pass http://deployx_api;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /actuator/ {
            proxy_pass http://deployx_api;
            proxy_set_header Host localhost;
        }

        location / {
            proxy_pass http://deployx_dashboard;
            proxy_set_header Host $host;
        }
    }
}
